[workspace]
members = [
  "crates/tx4-core",
  "crates/tx4-go-pion-sys",
  "crates/tx4-go-pion",
  "crates/tx4-signal-core",
#  "crates/tx4-signal-srv",
#  "crates/tx4-signal-cli",
  "crates/tx4-demo",
]
