[package]
name = "tx4-demo"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, features = [ "full" ] }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tx4 = { workspace = true }
